In [2]:
import torch
torch.where(torch.tensor([[1, 0, 1, 0, 1]]) == 1)

(tensor([0, 0, 0]), tensor([0, 2, 4]))

In [5]:
import torch

A = torch.tensor([1, 2, 3, 2, 4, 2, 2, 6])
B = torch.tensor([1, 2, 3, 4, 5, 6, 7, 8])

# 1. 找 mask
mask = (A == 2)

# 2. 每个位置的重复次数
repeat_times = torch.ones_like(A)
repeat_times[mask] = 2

# 3. 扩展 A 和 B
A_expanded = torch.repeat_interleave(A, repeat_times)
B_expanded = torch.repeat_interleave(B, repeat_times)

# 4. 计算扩展后 index
# 原始 index
idx = torch.arange(len(A))

# 每个位置之前一共插入了多少个额外元素
offset = torch.cumsum(repeat_times - 1, dim=0)

# 只取 mask 位置的最终 index
expanded_idx = idx[mask] + offset[mask]

print(A_expanded)   # tensor([1, 2, 2, 3, 2, 2, 4])
print(B_expanded)   # tensor([1, 2, 2, 3, 4, 4, 5])
print(expanded_idx) # tensor([1, 4])

tensor([1, 2, 2, 3, 2, 2, 4, 2, 2, 2, 2, 6])
tensor([1, 2, 2, 3, 4, 4, 5, 6, 6, 7, 7, 8])
tensor([ 2,  5,  8, 10])
